apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  labels:
    app: log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
      - name: log
        image: logstash:6.8.11
        ports:
        - containerPort: 9600
