apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeip
  labels:
    app: edb
spec:
  selector:
    app: edb
  type: NodePort
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 31001
