apiVersion: v1
kind: Service
metadata:
  name: logstash-nodeip
  labels:
    app: log
spec:
  selector:
    app: log
  type: NodePort
  ports:
  - name: http
    port: 9600
    targetPort: 9600
    nodePort: 31002
