apiVersion: v1
kind: Service
metadata:
  name: nso-nodeip-22
  labels:
    app: nso
spec:
  selector:
    app: nso
  type: NodePort
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 31090
